import React from 'react'
import Margin from '../../hooks'
import Box from '@material-ui/core/Box'
import Typography from '@material-ui/core/Typography'
import useMediaQuery from '@material-ui/core/useMediaQuery';
import { makeStyles, useTheme } from '@material-ui/core/styles';
import Grid from '@material-ui/core/Grid';
import BackgroundImage from './banner_bg.png';

const useStyles = makeStyles((theme) => ({
  titleTextBox: {
    backgroundColor: '#fafafa',
  },
  boxBody : {
    color: '#616161',
  }
}));

function CryptographyBanner() {
  const classes = useStyles();
  const theme = useTheme();
  const sm = useMediaQuery(theme.breakpoints.down('sm'));

  return (
    <Box className={ classes.titleTextBox }>
      <Margin>
        <Box >
          <Grid container spacing={5}>
            <Grid item xs={12} sm={12} md={6} lg={6}>
              <Box pt={sm ? 0 : 5}>
                <img src={BackgroundImage} width="100%" alt="banner"/>
              </Box>
              
            </Grid>
            <Grid item xs={12} sm={12} md={6} lg={6}>
              <Typography variant="h3" align='left' style={{color: '#424242', fontWeight: 600}} gutterBottom>Cryptographically secure</Typography>
              <Box mt={3}>
                <Grid container spacing={3}>
                  <Grid item xs={12} sm={6} md={6} lg={6}>
                    <Typography variant="h6" align='left' style={{color: '#424242', fontWeight: 500}} gutterBottom>Guaranteed authenticity</Typography>
                    <Typography className={classes.boxBody} variant="body1" gutterBottom>
                      Each ticket purchase and transfer is secured by the THETA blockchain, and the ownership of each ticket is transparent to and verifiable by all.
                      This thereby eliminates virtually any form of ticket fraud.
                    </Typography>
                  </Grid>
                  <Grid item xs={12} sm={6} md={6} lg={6}>
                    <Typography variant="h6" align='left' style={{color: '#424242', fontWeight: 500}} gutterBottom>Secure verification</Typography>
                    <Typography className={classes.boxBody} variant="body1" gutterBottom>
                      Each ticket generates a QR code, which is a securely signed signature that expires after 1 minute.
                      This can only be generated by the person possessing the private key to the wallet that holds each ticket, 
                      thus proving ownership at event entry.
                    </Typography>
                  </Grid>
                  <Grid item xs={12} sm={6} md={6} lg={6}>
                    <Typography variant="h6" align='left' style={{color: '#424242', fontWeight: 500}} gutterBottom>Encrypted off-chain data</Typography>
                    <Typography className={classes.boxBody} variant="body1" gutterBottom>
                      Any metadata that is stored off-chain is encrypted with AES-128, using the randomly generated 160-bit Event ID as the key.
                      Only the hash of the Event ID is stored via a map onto the encrypted metadata.
                      This means that without knowing the Event ID, no one <i>(not even the admins!)</i> can see the contents of your event.
                    </Typography>
                  </Grid>
                </Grid>
              </Box>
            </Grid>
          </Grid>
        </Box>
      </Margin>
    </Box>
    
    
  )
}

export default CryptographyBanner
